### ISSUE TITLE
Braintree support

### ISSUE THREAD

**Issue by seandelaney** [moltin/shopkit#40]
We have Braintree setup for Moltin. Does Shopkit support Braintree? I can't see anything in the docs.

**Comment by notrab** [comment]
This isn’t something we support. Feel free to open a PR if it’s something you wish to add, alternatively you could clone and host this yourself 😎

**Comment by jesseschutt** [comment]
Thanks @notrab  - What does your [blog post](https://www.moltin.com/blog/embeddable-cart-and-checkout-comparison) mean when it says "Integration with any third party payment gateway"?

**Comment by notrab** [comment]
@jesseschutt this was an earlier BETA feature we have since removed. Since the library is open source you can make any modifications you need and host it yourself for full control.
